name: app_ciel
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.4
  flutter_blue_plus: ^1.34.5
  flutter_bluetooth_serial: ^0.4.0
  go_router: ^14.6.0
  hive: ^2.2.3   # ✅ Versión más reciente
  hive_flutter: ^1.1.0
  provider: ^6.1.2

dev_dependencies:
  build_runner: ^2.4.15
  hive_generator: ^2.0.1   # ✅ Agregado correctamente
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

